name: CI/CD
on:
  push: 
    branches:
      - main
    # 修改侦听的文件范围
    paths:
      - '.github/workflows/**'
      - 'src/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: log in Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: drinklesscola/blog-server:latest
      
      - name: Pull on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            /home/workspace/blog-server/deploy.sh

